version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # Main RabbitMQ port
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '#Ghazaryan1'
      MYSQL_DATABASE: barberx
      MYSQL_USER: 'hovo.kazaryan.01@gmail.com'
      MYSQL_PASSWORD: '#Ghazaryan1'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
